name: HTML and CSS Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Lint HTML
        run: htmlhint .

      - name: Lint CSS
        run: |
          npx stylelint "**/*.css"
